version: '3'
services:
  beacon-node:
    build:
      context: .
      dockerfile: beacon.Dockerfile
    # this matches the name that genesis will give this node
    container_name: beacon-node-service0
    image: gcr.io/whiteblock/ethdenver-prysm-beacon-node:latest
    ports:
     - '4000:4000'
     - '13000:13000'
  validator:
    build:
      context: .
      dockerfile: validator.Dockerfile
    # this matches the name that genesis will give this node
    container_name: validator-service0
    restart: always
    image: gcr.io/whiteblock/ethdenver-prysm-validator:latest
# volumes:
