services:
  - name: prysm-beacon
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    args:
      - --datadir=/data
      - --interop-num-validators=1024
      - --no-discovery
      - --interop-eth1data-votes
      - --enable-attestation-cache
      - --enable-ssz-cache
      - --enable-skip-slots-cache
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
  - name: prysm-validator
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    args:
      - --keymanager=interop
      - --keymanageropts='{"keys":1024}'
      - --bootstrap-node='/dns4/prysm-beacon/tcp/13000/p2p/16Uiu2HAmCKyAFZpQ8vXtepfdkCwKEbTEwKTY3XeE4aVmer4xgnyC'
      - --beacon-rpc-provider=prysm-beacon:4000
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
tests:
  - name: simple-prysm-exercise
    description: "run a prysm testnet and validate some blocks"
    wait-for: 10 m
    system:
      - name: beacon-node-deploy
        type: prysm-beacon
        count: 1
      - name: validator-deploy
        type: prysm-validator
        count: 1
