services:
  - name: beacon-node
    image: gcr.io/whiteblock/ethdenver-prysm-beacon-node:latest
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
  - name: validator
    image: gcr.io/whiteblock/ethdenver-prysm-validator:latest
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
tests:
  - name: simple-prysm-exercise
    description: "run a prysm testnet and validate some blocks"
    wait-for: 2 m #wait for this amount of time before starting validators
    system:
      - name: beacon-node-deploy
        type: beacon-node
        count: 1
        resources:
           networks:
             - name: common-network
    phases:
      - name: validators
        system:
        - name: validator-deploy
          type: validator
          count: 1
          resources:
             networks:
               - name: common-network
