services:
  - name: prysm-beacon
    image: gcr.io/whiteblock/ethdenver-prysm-beacon-node:latest
    resources:
      cpus: 4
      memory: 4 GB
      storage: 10 GiB
  - name: prysm-validator
    image: gcr.io/whiteblock/ethdenver-prysm-validator:latest
    resources:
      cpus: 1
      memory: 1 GB
      storage: 1 GiB
tests:
  - name: simple-prysm-exercise
    description: "run a prysm testnet and validate some blocks"
    wait-for: 10 m
    system:
      - name: beacon-node-deploy
        type: prysm-beacon
        count: 1
      - name: validator-deploy
        type: prysm-validator
        count: 1
